export type PdfRenderConfiguration = {
  primaryColor: string;
  secondaryColor: string;
  headerFont: string;
  bodyFont: string;
  footerFont: string;
  headerSize: number;
  bodySize: number;
  footerSize: number;
  headerBold: boolean;
  bodyBold: boolean;
  footerBold: boolean;
  alignment: string;
  logo?: string;
};

type RenderInput = {
  documentType: string;
  data: Record<string, unknown>;
  configuration: PdfRenderConfiguration;
  templateName: string;
};

const escapeHtml = (value: unknown) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

const labelize = (key: string) =>
  key.replace(/([A-Z])/g, " $1").replace(/^./, (char) => char.toUpperCase());

export const renderDocumentHtml = ({ documentType, data, configuration, templateName }: RenderInput) => {
  const primary = configuration.primaryColor;
  const secondary = configuration.secondaryColor;
  const align = configuration.alignment;
  const title = templateName || labelize(documentType);
  const rows = Object.entries(data)
    .map(
      ([key, value]) => `
        <tr>
          <th>${escapeHtml(labelize(key))}</th>
          <td>${escapeHtml(value)}</td>
        </tr>
      `
    )
    .join("");

  return `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      @page { margin: 32px; }
      body {
        color: #111827;
        font-family: "${configuration.bodyFont}", Arial, sans-serif;
        font-size: ${configuration.bodySize}px;
        margin: 0;
      }
      .document {
        border: 1px solid ${secondary};
        min-height: 930px;
      }
      .header {
        align-items: center;
        background: ${primary};
        color: #fff;
        display: flex;
        gap: 18px;
        justify-content: ${align === "right" ? "flex-end" : align === "center" ? "center" : "flex-start"};
        padding: 28px 34px;
        text-align: ${align};
      }
      .logo {
        background: #fff;
        border-radius: 6px;
        max-height: 54px;
        max-width: 140px;
        object-fit: contain;
        padding: 6px;
      }
      h1 {
        font-family: "${configuration.headerFont}", Arial, sans-serif;
        font-size: ${configuration.headerSize}px;
        font-weight: ${configuration.headerBold ? 700 : 400};
        margin: 0;
      }
      .meta {
        border-bottom: 4px solid ${secondary};
        color: ${primary};
        font-weight: 700;
        padding: 18px 34px;
        text-align: ${align};
      }
      .content {
        padding: 30px 34px;
      }
      table {
        border-collapse: collapse;
        width: 100%;
      }
      th {
        background: ${secondary};
        color: #fff;
        padding: 12px;
        text-align: left;
        width: 34%;
      }
      td {
        border-bottom: 1px solid #d1d5db;
        font-weight: ${configuration.bodyBold ? 700 : 400};
        padding: 12px;
      }
      .summary {
        border: 1px solid ${secondary};
        margin-top: 28px;
        padding: 18px;
        text-align: ${align};
      }
      .footer {
        color: #111827;
        font-family: "${configuration.footerFont}", Arial, sans-serif;
        font-size: ${configuration.footerSize}px;
        font-weight: ${configuration.footerBold ? 700 : 400};
        padding: 24px 34px;
        text-align: ${align};
      }
    </style>
  </head>
  <body>
    <main class="document">
      <header class="header">
        ${configuration.logo ? `<img class="logo" src="${escapeHtml(configuration.logo)}" alt="Logo" />` : ""}
        <h1>${escapeHtml(title)}</h1>
      </header>
      <section class="meta">${escapeHtml(labelize(documentType))} generated from the active template configuration</section>
      <section class="content">
        <table>${rows}</table>
        <div class="summary">All styling in this document is driven by the active template configuration.</div>
      </section>
      <footer class="footer">Generated by Dynamic PDF Template Management System</footer>
    </main>
  </body>
</html>`;
};
