import { useTemplateStore } from "../store/templateStore";

const labelize = (key: string) => key.replace(/([A-Z])/g, " $1").replace(/^./, (char) => char.toUpperCase());

export const LivePreview = () => {
  const selectedTemplate = useTemplateStore((state) => state.selectedTemplate);
  const configuration = useTemplateStore((state) => state.configuration);
  const previewCategory = useTemplateStore((state) => state.previewCategory);
  const previewData = useTemplateStore((state) => state.previewData);

  return (
    <section className="sticky top-4 rounded-md border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950">
      <h2 className="mb-4 text-sm font-semibold text-slate-950 dark:text-white">Live Preview</h2>
      <div
        className="mx-auto min-h-[620px] max-w-[520px] border bg-white text-black shadow-soft"
        style={{ borderColor: configuration.secondaryColor, fontFamily: configuration.bodyFont, fontSize: configuration.bodySize }}
      >
        <div
          className="flex items-center gap-4 px-6 py-6 text-white"
          style={{
            backgroundColor: configuration.primaryColor,
            justifyContent:
              configuration.alignment === "right" ? "flex-end" : configuration.alignment === "center" ? "center" : "flex-start",
            textAlign: configuration.alignment
          }}
        >
          {configuration.logo && <img alt="" className="max-h-12 max-w-28 rounded bg-white p-1" src={configuration.logo} />}
          <h3
            className="m-0"
            style={{
              fontFamily: configuration.headerFont,
              fontSize: configuration.headerSize,
              fontWeight: configuration.headerBold ? 700 : 400
            }}
          >
            {selectedTemplate?.name ?? "Select a Template"}
          </h3>
        </div>
        <div className="border-b-4 px-6 py-3 font-semibold" style={{ borderColor: configuration.secondaryColor, color: configuration.primaryColor, textAlign: configuration.alignment }}>
          {labelize(previewCategory)}
        </div>
        <div className="p-6">
          <table className="w-full border-collapse">
            <tbody>
              {Object.entries(previewData).map(([key, value]) => (
                <tr key={key}>
                  <th className="w-2/5 px-3 py-3 text-left text-white" style={{ backgroundColor: configuration.secondaryColor }}>
                    {labelize(key)}
                  </th>
                  <td className="border-b border-slate-200 px-3 py-3" style={{ fontWeight: configuration.bodyBold ? 700 : 400 }}>
                    {String(value)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="mt-6 border p-4" style={{ borderColor: configuration.secondaryColor, textAlign: configuration.alignment }}>
            Saved settings are reflected here instantly.
          </div>
        </div>
        <footer
          className="px-6 py-5"
          style={{
            fontFamily: configuration.footerFont,
            fontSize: configuration.footerSize,
            fontWeight: configuration.footerBold ? 700 : 400,
            textAlign: configuration.alignment
          }}
        >
          Generated by Dynamic PDF Template Management System
        </footer>
      </div>
    </section>
  );
};
